const convodisplayStyles = () => ({
  convoheader: {
    width: "70vw",
    height: "80px",
    marginLeft: "30%",
    background: "#F0FFFF",
    padding: "20px",
    position: "fixed",
    zIndex: "1",
    boxSizing: "border-box",
  },
  messages: {
    display: "flex",
    flexDirection: "column-reverse",
    alignItems: "center",
    width: "70vw",
    marginLeft: "30%",
    position: "absolute",
    top: "80px",
    overflow: "auto",
    height: "calc(100vh - 150px)",
    background: "#FFFFF3",
    boxSizing: "border-box",
    border: "10px #FFFFF3 solid",
  },
  messagesUser: {
    width: "30%",
    background: "#67A9A8",
    float: "right",
    clear: "both",
    padding: "20px",
    borderRadius: "15px",
    marginLeft: "65%",
    wordWrap: "break-word",
    boxSizing: "border-box",
    marginTop: "10px",
    color: "#FFFFFD",
  },
  messagesOther: {
    width: "30%",
    background: "#DCC497",
    float: "left",
    clear: "both",
    padding: "20px",
    borderRadius: "15px",
    marginRight: "65%",
    wordWrap: "break-word",
    boxSizing: "border-box",
    marginTop: "10px",
  },
});

export default convodisplayStyles;
